services:
  - type: web
    name: psychiatrist-backend
    env: python
    rootDir: Backend
    plan: free
    buildCommand: "pip install uv && uv pip install -r requirements.txt && crewai install"
    startCommand: "uvicorn src.assignment.main:app --reload --host 127.0.0.1 --port 8000"
    envVars:
      - key: MONGO_URI
      - key: DB_NAME
      - key: VITE_GOOGLE_API_KEY

  - type: web
    name: psychiatrist-frontend
    env: node
    rootDir: frontend
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npx serve -s dist -l 3000"
    envVars:
      - key: VITE_GOOGLE_API_KEY
        value: "AIzaSyCGxv_Wa2v3kmtyaXMZhfNOjErfMrm2BVQ"
