services:
  - type: web
    name: psychiatrist-backend
    env: python
    rootDir: Backend
    plan: free
    buildCommand: "pip install -r requirements.txt && crewai install"
    startCommand: "uvicorn src.assignment.main:app --reload --host 0.0.0.0 --port 8000"
    envVars:
      - key: MONGO_URI
        value: "mongodb+srv://bhanderiprince03_db_user:VbKVXbCPnOuSLm1z@cluster0.pgvlefg.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
      - key: DB_NAME
        value: "virtual_psychiatrist"
      - key: VITE_GOOGLE_API_KEY
        value: "AIzaSyCGxv_Wa2v3kmtyaXMZhfNOjErfMrm2BVQ"

  - type: web
    name: psychiatrist-frontend
    env: node
    rootDir: frontend
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npx serve -s dist -l 3000"
    envVars:
      - key: VITE_GOOGLE_API_KEY
        value: "AIzaSyCGxv_Wa2v3kmtyaXMZhfNOjErfMrm2BVQ"
